### PR TITLE
fix(#1): option for notes to be destroyed

### PR DESCRIPTION
**Pull request by kartikpandey2**
#1 
Added new button: On click to this button will not destroy the message, and it will be valid for 1 hour, 
after 1 hour it will automatically destroy.

### CODE REVIEW

**Comment by joshterrill** [comment]
I think there was some confusion on me describing the issue. I don't want the reader to decide when the message gets destroyed. I want the sender to define it before the message gets generated. I also believe there's a better solution for deleting other than using a timeout. There are some issues around that like if there server needs to be restarted, it'll get rid of all the timeouts. I'm thinking it would be better to implement a cron scheduler that gets created for each note, and on server startup, it looks at the database for messages that need to get destroyed, sees what time they should be destroyed at, and then creates a scheduler or countdown for that time.

**Comment by kartikpandey2** [comment]
ok, I think the better way to remove messages from DB is to create TTL index.

**Comment by joshterrill** [comment]
Going back to the original issue I opened https://github.com/joshterrill/hushnote/issues/1 I believe it would be best to give the user an option to either have it be a once-read-destroy or a destroy on timer message.  I also see there are a few things like the number `3600000` at the bottom of `src/api/index.js` not wrapped in any method, is this intentional? It also appears that all messages get destroyed after only an hour, the user needs to be able to define how many minutes or hours it should stay alive. Also, the wording on the button "Are you sure you want to read this message" would need to be changed in the event that it is a message that gets destroyed after a period of time because currently the button says that if you read the message you'd destroy it.

**Comment by kartikpandey2** [comment]
@joshterrill OK, I will make a change and will request PR.

**Comment by kartikpandey2** [comment]
@joshterrill Suppose user said message should be valid for 1 hour. Then this validation starts after authorized user see's the message or it should start as soon as he posted message .?

**Comment by joshterrill** [comment]
As soon as he posts the message/as soon as the message gets saved.

**Comment by joshterrill** [comment]
This was fixed in https://github.com/joshterrill/hushnote/pull/3. Thanks for contributing.

**Pull request closed without merging**
