### PR TITLE
Added support for Lando local enviroment

### PR DESCRIPTION
**Pull request by mgi1982**
I added support for Lando so local enviroment is easier to setup and use.

### CODE REVIEW

**Comment by mgi1982** [comment]
Added support for Lando for local environments and addressed #1

**Comment by joshterrill** [comment]
I'll take a look at this in the next day. Thanks for the PR.

**Comment by joshterrill** [comment]
Is this PR done yet? It doesn't appear to be working. Before I send over a list of things I saw, I wanted to first see what status it was at.

**Comment by mgi1982** [comment]
The PR is done and seems to be working fine on my end. Please send the list of issues you detected so I can fix/correct them.

**Comment by joshterrill** [comment]
It looks good, I think there's just one other thing I'd change. Right now a user can check both destroy message on read, and set a time. I think it needs to be one or the other. I wrote a little javascript and html on jsfiddle to show kind of what I'm thinking would be a good user experience: http://jsfiddle.net/sk6n8pm3/

 Would you be able to do something like that?

**Comment by joshterrill** [comment]
@mgi1982 And if you can't do what I mentioned above, let me know and I can finish it off.

**Comment by mgi1982** [comment]
I'll try to I'd it by tomorrow

**Comment by mgi1982** [comment]
Done, please check the PR now.

**Comment by joshterrill** [comment]
@mgi1982 I'll merge it, but there's still one thing that's not right from the jsfiddle I sent. The "Select One" option is set to a value of 0 instead of null, so when you go back and forth from the radio buttons, instead of it going back to "Select One", it just goes to an empty dropdown with no value. I'll merge the code and fix that part myself. Thanks for the help.

**Comment by joshterrill** [comment]
@mgi1982 It looks like the code for the ttl is not working. It gets destroyed every single time the note gets read. I'm reverting this pull request.

**Comment by mgi1982** [comment]
The TTL code will auto destroy notes that have expired. 
It does not change the previous functionality at all, meaning that notes can only be read once and then they get destroyed as usual, I assumed this is what you wanted. 

⁣Sent from BlueMail ​

**Comment by joshterrill** [comment]
That's what I mean though, I tested it and it does not work correctly. I set the ttl for 1 minute, visited the link, it asks if I want to destroy, I say yes, and then I visit the link again, and it says it's already destroyed. This note was not expired yet.

**Comment by mgi1982** [comment]
What you just described sounds like correct behavior: you opened a note before the TTL expired, destroyed it and when tried to open it again you got an error because the note was already destroyed. 

Maybe it'll be better if you describe step by step what you expected happens so I can understand better? 

⁣Sent from BlueMail ​

**Comment by joshterrill** [comment]
There is some confusion. The user should be able to set a time limit for the note to be destroyed. If I set it for 5 minutes, after 5 minutes, the note should be destroyed. Currently, it gets destroyed no matter how long I set it for right when the user reads it, this is incorrect. There needs to be two options, one option to destroy the note once read, and another option to destroy the note after a certain amount of time, as defined by the user.

**Comment by joshterrill** [comment]
Following up to my last message, if a user sets the ttl to be 5 minutes, they should be able to read the message however many times they want to until the 5 minutes is up, and then the note gets destroyed.

**Comment by mgi1982** [comment]
I see, I'll make those changes and will resubmit then, thanks for the clarification 

⁣Sent from BlueMail ​

**Comment by joshterrill** [comment]
Please do a new PR, thanks.

**Pull request merged**
